/**
Copyright 2011-2015 Timothy James Hruska (tjhruska@yahoo.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
  
package com.tjhruska.mc.domain.system

import org.springframework.beans.factory.annotation.Autowired
import static org.junit.Assert.*
import org.junit.Before
import org.junit.Ignore

import com.tjhruska.mc.database.BaseDomain
import com.tjhruska.mc.database.DaoDomain
import com.tjhruska.mc.database.test.GeneratedDomainAndDaoTest
import com.tjhruska.mc.domain.system.EnumerationLink
import com.tjhruska.mc.domain.system.EnumerationLinkTest
  

//    Class contains database constraints which can't be accommodated in autogenerated code.
//    To activate test: extend test class, and tweak fields with constraints to match database expectations.
//    (Extended class won't be wiped out on regeneration, and must continue to match database expectations.)
@Ignore 
class EnumerationLinkValueTest extends GeneratedDomainAndDaoTest {
  
  @Autowired
  DaoDomain<EnumerationLinkValue> enumerationLinkValueDao

  @Autowired
  DaoDomain<EnumerationLink> enumerationLinkDao
  EnumerationLinkTest enumerationLinkTest

  @Before
  public void setup() {

    enumerationLinkTest = new EnumerationLinkTest()
    enumerationLinkTest.enumerationLinkDao = enumerationLinkDao
  }

  @Override
  public DaoDomain getDao() {
    enumerationLinkValueDao
  }

  EnumerationLink enumerationLink

  @Override
  public BaseDomain getTestObject(Integer number, Integer sequence) {
    EnumerationLinkValue enumerationLinkValue = new EnumerationLinkValue()
    
    if (enumerationLink == null) {
      enumerationLinkValue.setEnumerationLink(enumerationLinkTest.persistTestObject(number))
      enumerationLinkValue.enumerationLink.linkValues.add(enumerationLinkValue)
    } else {
      enumerationLinkValue.setEnumerationLink(enumerationLink)
    }
    enumerationLinkValue.setEnumerationValueAId(number)
    enumerationLinkValue.setEnumerationValueBId(number)
    enumerationLinkValue.setName("name${number}")
    enumerationLinkValue.setDescription("description${number}")
    enumerationLinkValue.setSequence((Short)sequence)
    enumerationLinkValue.setColumn1Value("column1_value${number}")
    enumerationLinkValue.setColumn2Value("column2_value${number}")
    enumerationLinkValue.setColumn3Value("column3_value${number}")
    enumerationLinkValue.setColumn4Value("column4_value${number}")
    enumerationLinkValue.setColumn5Value("column5_value${number}")
    
    enumerationLinkValue
  }

  @Override
  public BaseDomain updateDomainObject(Integer number, BaseDomain domain) {
    EnumerationLinkValue source = getTestObject(number, 0)
    EnumerationLinkValue target = (EnumerationLinkValue)domain
    target.setEnumerationLink(source.getEnumerationLink())
    target.setEnumerationValueAId(source.getEnumerationValueAId())
    target.setEnumerationValueBId(source.getEnumerationValueBId())
    target.setName(source.getName())
    target.setDescription(source.getDescription())
    target.setSequence(source.getSequence())
    target.setColumn1Value(source.getColumn1Value())
    target.setColumn2Value(source.getColumn2Value())
    target.setColumn3Value(source.getColumn3Value())
    target.setColumn4Value(source.getColumn4Value())
    target.setColumn5Value(source.getColumn5Value())

    return source
  }

  @Override
  public void assertDomainUpdates(BaseDomain expected, BaseDomain actual) {
    EnumerationLinkValue expectedD = (EnumerationLinkValue)expected
    EnumerationLinkValue actualD = (EnumerationLinkValue)actual
    enumerationLinkTest.assertDomainUpdates(expectedD.getEnumerationLink(), actualD.getEnumerationLink())
    assertEquals("enumerationValueA is different than expected", expectedD.getEnumerationValueAId(), actualD.getEnumerationValueAId())
    assertEquals("enumerationValueB is different than expected", expectedD.getEnumerationValueBId(), actualD.getEnumerationValueBId())
    assertEquals("name is different than expected", expectedD.getName(), actualD.getName())
    assertEquals("description is different than expected", expectedD.getDescription(), actualD.getDescription())
    assertEquals("sequence is different than expected", expectedD.getSequence(), actualD.getSequence())
    assertEquals("column1Value is different than expected", expectedD.getColumn1Value(), actualD.getColumn1Value())
    assertEquals("column2Value is different than expected", expectedD.getColumn2Value(), actualD.getColumn2Value())
    assertEquals("column3Value is different than expected", expectedD.getColumn3Value(), actualD.getColumn3Value())
    assertEquals("column4Value is different than expected", expectedD.getColumn4Value(), actualD.getColumn4Value())
    assertEquals("column5Value is different than expected", expectedD.getColumn5Value(), actualD.getColumn5Value())
  }
  
  @Override
  void deleteObject(BaseDomain domain) {
    if (domain == null) {
      return
    }
    EnumerationLinkValue target = (EnumerationLinkValue)domain

    enumerationLinkTest.deleteObject(target.enumerationLink)
    enumerationLinkValueDao.delete(target)
    enumerationLinkValueDao.flush()
    enumerationLinkValueDao.evict(target)
  }
}