/**
Copyright 2011-2015 Timothy James Hruska (tjhruska@yahoo.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
  
package com.tjhruska.mc.domain.system

import org.springframework.context.annotation.Lazy
import org.springframework.beans.factory.annotation.Autowired
import static org.junit.Assert.*
import org.junit.Before
import org.junit.Ignore

import groovy.util.logging.Slf4j

import com.tjhruska.mc.database.BaseDomain
import com.tjhruska.mc.database.DaoDomain
import com.tjhruska.mc.database.test.GeneratedDomainAndDaoTestIface

import com.tjhruska.mc.database.test.GeneratedDomainAndDaoTest
import com.tjhruska.mc.enums.TableCreationRule
import com.tjhruska.mc.domain.system.Column
import com.tjhruska.mc.domain.system.Index
import java.util.ArrayList
import java.util.HashSet
import java.util.List
import java.util.Set
import com.tjhruska.mc.domain.system.Column
import com.tjhruska.mc.domain.system.ColumnTest
import com.tjhruska.mc.domain.system.Index
import com.tjhruska.mc.domain.system.IndexTest
  

//    Class contains database constraints which can't be accommodated in autogenerated code.
//    To activate test: extend test class, and tweak fields with constraints to match database expectations.
//    (Extended class won't be wiped out on regeneration, and must continue to match database expectations.)
@Ignore 
@Slf4j
class TableTestImpl extends GeneratedDomainAndDaoTest implements TableTest {
  
  @Autowired
  DaoDomain<Table> tableDao

  @Autowired
  @Lazy
  ColumnTest columnTest

  @Autowired
  @Lazy
  IndexTest indexTest

  @Override
  public DaoDomain getDao() {
    tableDao
  }


  @Override
  public BaseDomain getTestObject(Integer number, Integer sequence, Boolean addChildrenFlag) {
    Table table = new Table()
    
    table.setSystemNoModifyFlag(number == 0 || 3%number == 0)
    table.setName("name${number}")
    table.setDescription("description${number}")
    table.setNameCamelCase("name_camel_case${number}")
    table.setTableCreationRule(TableCreationRule.getTableCreationRuleBySequence(1))
    table.setSuppressTableChangesFlag(number == 0 || 8%number == 0)
    table.setCreateIUDTableFlag(number == 0 || 9%number == 0)
    table.setSchemaName("schema_name${number}")
    table.setWithinCreateSQL("within_create_sql${number}")
    table.setPostCreateSQL("post_create_sql${number}")
    table.setCreatePOJOFlag(number == 0 || 13%number == 0)
    table.setSrcFolderTag("src_folder_tag${number}")
    table.setSuppressPOJOChangesFlag(number == 0 || 15%number == 0)
    table.setJavaPackage("java_package${number}")
    table.setJavaFullyQualifiedSuperClass("java_fq_superclass${number}")
    table.setConstructorFromFieldsFlag(number == 0 || 18%number == 0)
    table.setClassImports("class_imports${number}")
    table.setClassAnnotationsCode("class_annotation_code${number}")
    table.setExtraJavaCode("extra_java_code${number}")
    table.setCreateORMFlag(number == 0 || 22%number == 0)
    table.setSuppressORMChangesFlag(number == 0 || 23%number == 0)
    table.setExtraORMCode("extra_orm_code${number}")
    table.setOrmDiscriminatorColumnId(number)
    table.setCreateGUIDataServiceFlag(number == 0 || 26%number == 0)
    table.setSuppressGUIDataServiceChangesFlag(number == 0 || 27%number == 0)
    table.setGuiPagifyFlag(number == 0 || 28%number == 0)
    table.setGuiRecordsPerPage((Short)(29 * number))
    table.setGuiPickerDescriptionColumnId(number)
    
    List<Column> columns = new ArrayList()
    if (addChildrenFlag && columnTest != null) {
      columnTest.table = table
      (1..(number+2)).each { i ->
      columns.add(columnTest.getTestObject(i+(10*number), i-1))
      }
    }
    table.setColumns(columns)

    Set<Index> indexes = new HashSet()
    if (addChildrenFlag && indexTest != null) {
      indexTest.table = table
      (1..(number+2)).each { i ->
      indexes.add(indexTest.getTestObject(i+(10*number), i-1))
      }
    }
    table.setIndexes(indexes)

    table
  }

  @Override
  public BaseDomain updateDomainObject(Integer number, BaseDomain domain) {
    Table source = getTestObject(number, 0)
    Table target = (Table)domain
    target.setSystemNoModifyFlag(source.getSystemNoModifyFlag())
    target.setName(source.getName())
    target.setDescription(source.getDescription())
    target.setNameCamelCase(source.getNameCamelCase())
    target.setTableCreationRule(source.getTableCreationRule())
    target.setSuppressTableChangesFlag(source.getSuppressTableChangesFlag())
    target.setCreateIUDTableFlag(source.getCreateIUDTableFlag())
    target.setSchemaName(source.getSchemaName())
    target.setWithinCreateSQL(source.getWithinCreateSQL())
    target.setPostCreateSQL(source.getPostCreateSQL())
    target.setCreatePOJOFlag(source.getCreatePOJOFlag())
    target.setSrcFolderTag(source.getSrcFolderTag())
    target.setSuppressPOJOChangesFlag(source.getSuppressPOJOChangesFlag())
    target.setJavaPackage(source.getJavaPackage())
    target.setJavaFullyQualifiedSuperClass(source.getJavaFullyQualifiedSuperClass())
    target.setConstructorFromFieldsFlag(source.getConstructorFromFieldsFlag())
    target.setClassImports(source.getClassImports())
    target.setClassAnnotationsCode(source.getClassAnnotationsCode())
    target.setExtraJavaCode(source.getExtraJavaCode())
    target.setCreateORMFlag(source.getCreateORMFlag())
    target.setSuppressORMChangesFlag(source.getSuppressORMChangesFlag())
    target.setExtraORMCode(source.getExtraORMCode())
    target.setOrmDiscriminatorColumnId(source.getOrmDiscriminatorColumnId())
    target.setCreateGUIDataServiceFlag(source.getCreateGUIDataServiceFlag())
    target.setSuppressGUIDataServiceChangesFlag(source.getSuppressGUIDataServiceChangesFlag())
    target.setGuiPagifyFlag(source.getGuiPagifyFlag())
    target.setGuiRecordsPerPage(source.getGuiRecordsPerPage())
    target.setGuiPickerDescriptionColumnId(source.getGuiPickerDescriptionColumnId())

    target.columns.each {
      columnTest.getDao().delete(it)
    }
    target.columns.clear()
    source.columns.each {
      it.table = target
    }
    target.columns.addAll(source.columns)
    target.indexes.each {
      indexTest.getDao().delete(it)
    }
    target.indexes.clear()
    source.indexes.each {
      it.table = target
    }
    target.indexes.addAll(source.indexes)

    return source
  }

  @Override
  public void assertDomainUpdates(BaseDomain expected, BaseDomain actual) {
    Table expectedD = (Table)expected
    Table actualD = (Table)actual
    assertEquals("systemNoModifyFlag is different than expected", expectedD.getSystemNoModifyFlag(), actualD.getSystemNoModifyFlag())
    assertEquals("name is different than expected", expectedD.getName(), actualD.getName())
    assertEquals("description is different than expected", expectedD.getDescription(), actualD.getDescription())
    assertEquals("nameCamelCase is different than expected", expectedD.getNameCamelCase(), actualD.getNameCamelCase())
    assertEquals("tableCreationRule is different than expected", expectedD.getTableCreationRule(), actualD.getTableCreationRule())
    assertEquals("suppressTableChangesFlag is different than expected", expectedD.getSuppressTableChangesFlag(), actualD.getSuppressTableChangesFlag())
    assertEquals("createIUDTableFlag is different than expected", expectedD.getCreateIUDTableFlag(), actualD.getCreateIUDTableFlag())
    assertEquals("schemaName is different than expected", expectedD.getSchemaName(), actualD.getSchemaName())
    assertEquals("withinCreateSQL is different than expected", expectedD.getWithinCreateSQL(), actualD.getWithinCreateSQL())
    assertEquals("postCreateSQL is different than expected", expectedD.getPostCreateSQL(), actualD.getPostCreateSQL())
    assertEquals("createPOJOFlag is different than expected", expectedD.getCreatePOJOFlag(), actualD.getCreatePOJOFlag())
    assertEquals("srcFolderTag is different than expected", expectedD.getSrcFolderTag(), actualD.getSrcFolderTag())
    assertEquals("suppressPOJOChangesFlag is different than expected", expectedD.getSuppressPOJOChangesFlag(), actualD.getSuppressPOJOChangesFlag())
    assertEquals("javaPackage is different than expected", expectedD.getJavaPackage(), actualD.getJavaPackage())
    assertEquals("javaFullyQualifiedSuperClass is different than expected", expectedD.getJavaFullyQualifiedSuperClass(), actualD.getJavaFullyQualifiedSuperClass())
    assertEquals("constructorFromFieldsFlag is different than expected", expectedD.getConstructorFromFieldsFlag(), actualD.getConstructorFromFieldsFlag())
    assertEquals("classImports is different than expected", expectedD.getClassImports(), actualD.getClassImports())
    assertEquals("classAnnotationsCode is different than expected", expectedD.getClassAnnotationsCode(), actualD.getClassAnnotationsCode())
    assertEquals("extraJavaCode is different than expected", expectedD.getExtraJavaCode(), actualD.getExtraJavaCode())
    assertEquals("createORMFlag is different than expected", expectedD.getCreateORMFlag(), actualD.getCreateORMFlag())
    assertEquals("suppressORMChangesFlag is different than expected", expectedD.getSuppressORMChangesFlag(), actualD.getSuppressORMChangesFlag())
    assertEquals("extraORMCode is different than expected", expectedD.getExtraORMCode(), actualD.getExtraORMCode())
    assertEquals("ormDiscriminatorColumn is different than expected", expectedD.getOrmDiscriminatorColumnId(), actualD.getOrmDiscriminatorColumnId())
    assertEquals("createGUIDataServiceFlag is different than expected", expectedD.getCreateGUIDataServiceFlag(), actualD.getCreateGUIDataServiceFlag())
    assertEquals("suppressGUIDataServiceChangesFlag is different than expected", expectedD.getSuppressGUIDataServiceChangesFlag(), actualD.getSuppressGUIDataServiceChangesFlag())
    assertEquals("guiPagifyFlag is different than expected", expectedD.getGuiPagifyFlag(), actualD.getGuiPagifyFlag())
    assertEquals("guiRecordsPerPage is different than expected", expectedD.getGuiRecordsPerPage(), actualD.getGuiRecordsPerPage())
    assertEquals("guiPickerDescriptionColumn is different than expected", expectedD.getGuiPickerDescriptionColumnId(), actualD.getGuiPickerDescriptionColumnId())
    assertEquals("size of columns is different than expected", expectedD.columns.size(), actualD.columns.size())
    assertEquals("size of indexes is different than expected", expectedD.indexes.size(), actualD.indexes.size())
  }
  
  @Override
  void deleteObject(BaseDomain domain) {
    if (domain == null) {
      return
    }
    Table target = (Table)domain

    tableDao.delete(target)
    tableDao.flush()
    tableDao.evict(target)
  }
}